### ISSUE TITLE
Add Lint Commit Messages Workflow 🚀

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#598]
Description:
Currently, our repository lacks a consistent and reliable mechanism to enforce commit message linting, which is essential for maintaining a clean and well-structured commit history. To address this, we propose adding a new workflow named "Lint Commit Messages" using the "commitlint-github-action" for automated commit message linting. This workflow will be triggered on both pull_request and push events, ensuring that commit messages meet our defined standards whenever code changes are made in the repository.

Workflow YAML:

```yaml
name: Lint Commit Messages

on:
  pull_request:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
```

Once this workflow is implemented, every time code is pushed to GitHub or a pull request is created/updated, the commitlint action will be triggered, automatically checking the commit messages for compliance with our defined rules.
